site_name: MN LAB Platform Documentation
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Light mode

nav:
  - About the Project: index.md
  - Arches for JU Excavations:
    - About: arches-for-ju-excavations/about.md
    - Access Control & Permissions: arches-for-ju-excavations/access-control.md
    - Workflows: 
      - Define Coordinate System: arches-for-ju-excavations/workflows/define-coordinate-system.md
      - Assign Coordinate System: arches-for-ju-excavations/workflows/assign-coordinate-system.md
      - GNSS/Total Station Data Import: arches-for-ju-excavations/workflows/gnss-ts-data-import.md
      - Upload Basemap Overlay Layer: arches-for-ju-excavations/workflows/upload-basemap-overlay-layer.md
      - Add Digital Resource 3D: arches-for-ju-excavations/workflows/add-digital-resource-3d.md
      - Annotate Digital Resource 3D: arches-for-ju-excavations/workflows/annotate-digital-resource-3d.md
      - Add Digital Resource IIIF: arches-for-ju-excavations/workflows/add-digital-resource-iiif.md
      - Add to Digital Resource IIIF: arches-for-ju-excavations/workflows/add-to-digital-resource-iiif.md
      - Annotate Digital Resource IIIF: arches-for-ju-excavations/workflows/annotate-digital-resource-iiif.md
      - Add RTI Resource: arches-for-ju-excavations/workflows/add-rti-resource.md
      - Add Pottery Collection: arches-for-ju-excavations/workflows/add-pottery-collection.md
      - Add Pottery Records: arches-for-ju-excavations/workflows/add-pottery-records.md
    - Plugins:
      - Map Plugin: arches-for-ju-excavations/plugins/map-plugin.md
  - AfS for Mare Nostrum Lab:
    - About: afs-for-mare-nostrum-lab/about.md
    - 3D Model Workflow: afs-for-mare-nostrum-lab/3d-model-workflow.md
    - RTI Workflow: afs-for-mare-nostrum-lab/rti-workflow.md
  - Mare Nostrum LAB thesaurus:
    - Quick Start: mare-nostrum-thesaurus/quickstart.md
    - Account Management: mare-nostrum-thesaurus/account-management.md
    - Creating a New Record in the Thesaurus - Cradle: mare-nostrum-thesaurus/cradle.md
    - Mare Nostrum LAB thesaurus - Management: mare-nostrum-thesaurus/mare-nostrum-thesaurus-management.md
    - Appendices: mare-nostrum-thesaurus/appendices.md
  - Ontology Viewer:
    - Quick Start: ontology-viewer/quickstart.md
  - GeoNode:
    - About: geonode/about.md
    - MN Thesauri plugin: geonode/thesauri-plugin.md
  - Recogito:
    - Quick Start: recogito-studio/quickstart.md
    - Account Management: recogito-studio/account-management.md
    - Main Activities: recogito-studio/main-activities.md
    - Appendices: recogito-studio/appendices.md
  - Minions: 
    - Context Field Sheet Template: minions/context_field_sheet_template.md
    - Photogrammetric Documentation Workflow: minions/photogrammetric_documentation_workflow.md
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
