site_name: Mare Nostrum LAB
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Light mode

nav:
  - About Project: index.md
  - Arches for Excavation:
    - About: arches-for-excavation/about.md
    - Plugins: 
      - Define Coordinate System: arches-for-excavation/plugins/define-coordinate-system.md
      - Assign Coordinate System: arches-for-excavation/plugins/assign-coordinate-system.md
      - GNSS/Total Station Data Import: arches-for-excavation/plugins/gnss-ts-data-import.md
      - Upload Basemap Overlay Layer: arches-for-excavation/plugins/upload-basemap-overlay-layer.md
      - Add Digital Resource 3D: arches-for-excavation/plugins/add-digital-resource-3d.md
      - Annotate Digital Resource 3D: arches-for-excavation/plugins/annotate-digital-resource-3d.md
      - Add Digital Resource IIIF: arches-for-excavation/plugins/add-digital-resource-iiif.md
      - Add to Digital Resource IIIF: arches-for-excavation/plugins/add-to-digital-resource-iiif.md
      - Annotate Digital Resource IIIF: arches-for-excavation/plugins/annotate-digital-resource-iiif.md
      - Add RTI Resource: arches-for-excavation/plugins/add-rti-resource.md
      - Add Pottery Collection: arches-for-excavation/plugins/add-pottery-collection.md
      - Add Pottery Records: arches-for-excavation/plugins/add-pottery-records.md
  - Mare Nostrum Thesaurus:
    - Quick Start: mare-nostrum-thesaurus/quickstart.md
    - Account Management: mare-nostrum-thesaurus/account-management.md
    - Creating a New Record in the Thesaurus - Cradle: mare-nostrum-thesaurus/cradle.md
    - Mare Nostrum Thesaurus - Management: mare-nostrum-thesaurus/mare-nostrum-thesaurus-management.md
    - Appendices: mare-nostrum-thesaurus/appendices.md
  - Ontology Viewer:
    - Quick Start: ontology-viewer/quickstart.md
  - Recogito Studio:
    - Quick Start: recogito-studio/quickstart.md
    - Account Management: recogito-studio/account-management.md
    - Main Activities: recogito-studio/main-activities.md
    - Appendices: recogito-studio/appendices.md
    
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences